name: Publish NuGet package

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        description: "Project to publish"
        type: choice
        options:
          - TheTemplatedName
      version:
        description: "Version to publish"
        required: true
      publish_to_github_packages:
        description: "Publish to GitHub Packages"
        type: boolean
        required: true
        default: true
      publish_to_nuget_org:
        description: "Also publish to public nuget.org registry"
        type: boolean
        default: false
        required: true
      create_gh_release:
        description: "Create a github release"
        type: boolean
        default: false
        required: true
      prefix:
        description: "Prefix used at the beginning of namespaces"
        type: string
        default: ElboraiSoftware
        required: true

env:
  dotnet-version: "6.0.x"

jobs:
  build-test-publish:
    name: "${{ github.event.inputs.prefix }}.${{ github.event.inputs.project }} v${{ github.event.inputs.version }} (${{ matrix.os }})"
    strategy:
      matrix:
        os:
          - windows-latest
          # Uncomment if needed
          # - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Log inputs
        shell: pwsh
        run: Write-Host "${{ toJSON(github.event.inputs) }}"

      - name: Validate version
        uses: elboraisoftware/actions/validate_semantic_version@main
        with:
          version: "${{ github.event.inputs.version }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: .Net setup
        uses: elboraisoftware/actions/dotnet_setup@main
        with:
          os: "${{ runner.os }}"
          dotnet-version: "${{ env.dotnet-version }}"
          # Uncomment if private registry is used
          # github-packages-token: "${{ secrets.NUGET_PRIVATE_REGISTRY_TOKEN }}"

      - name: Build and test .Net projects
        uses: elboraisoftware/actions/dotnet_build_and_test@main
        with:
          configuration: Release
          use-msbuild: true

      - name: Pack and publish NuGet package
        uses: elboraisoftware/actions/dotnet_publish_nuget@main
        with:
          csproj-path: "${{ github.event.inputs.project }}/${{ github.event.inputs.project }}.csproj"
          version: "${{ github.event.inputs.version }}"
          package-name: "${{ github.event.inputs.prefix }}.${{ github.event.inputs.project }}"
          create-github-release: "${{ github.event.inputs.create_gh_release }}"
          github-release-git-tag: "${{ github.event.inputs.project }}-v${{ github.event.inputs.version }}"
          repository: "${{ github.repository }}"
          repository-owner: "${{ github.repository_owner }}"
          publish-to-github-packages: "${{ github.event.inputs.publish_to_github_packages }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          publish-to-nuget: "${{ github.event.inputs.publish_to_nuget_org }}"
          nuget-api-key: "${{ secrets.NUGET_API_KEY }}"
          use-msbuild: "${{ github.event.inputs.use-msbuild }}"
