name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnet-version:
          - "6.0.x"
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: .Net setup
        uses: elboraisoftware/actions/dotnet_setup@main
        with:
          dotnet-version: "${{ matrix.dotnet-version }}"
          # Uncomment if private registry is used
          # github-packages-token: "${{ secrets.NUGET_PRIVATE_REGISTRY_TOKEN }}"

      - name: Build and test .Net projects
        uses: elboraisoftware/actions/dotnet_build_and_test@main
        with:
          configuration: "${{ matrix.configuration }}"
